In [228]:
import pandas as pd
import numpy as np
df = pd.read_json("../data/raw/India-Food-Delivery-Time-Prediction.txt",)
df.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
0,0x4607,INDORES13DEL02,37.0,4.9,22.745049,75.892471,22.765049,75.912471,19-03-2022,11:33:33,11:45:29,conditions Sunny,High,2,Snack,motorcycle,0.0,No,Urban,(min) 24
1,0xb379,BANGRES18DEL02,34.0,4.5,12.913041,77.683237,13.043041,77.813237,25-03-2022,19:45:37,19:51:49,conditions Stormy,Jam,2,Snack,scooter,1.0,No,Metropolitian,(min) 33
2,0x5d6d,BANGRES19DEL01,23.0,4.4,12.914264,77.678400,12.924264,77.688400,19-03-2022,8:32:58,8:48:47,conditions Sandstorms,Low,0,Drinks,motorcycle,1.0,No,Urban,(min) 26
3,0x7a6a,COIMBRES13DEL02,38.0,4.7,11.003669,76.976494,11.053669,77.026494,05-04-2022,18:03:58,18:12:52,conditions Sunny,Medium,0,Buffet,motorcycle,1.0,No,Metropolitian,(min) 21
4,0x70a2,CHENRES12DEL01,32.0,4.6,12.972793,80.249982,13.012793,80.289982,26-03-2022,13:34:16,13:45:36,conditions Cloudy,High,1,Snack,scooter,1.0,No,Metropolitian,(min) 30

In [229]:
df.shape

(41953, 20)

In [230]:
df.columns

Index(['ID', 'Delivery_person_ID', 'Delivery_person_Age',
       'Delivery_person_Ratings', 'Restaurant_latitude',
       'Restaurant_longitude', 'Delivery_location_latitude',
       'Delivery_location_longitude', 'Order_Date', 'Time_Orderd',
       'Time_Order_picked', 'Weatherconditions', 'Road_traffic_density',
       'Vehicle_condition', 'Type_of_order', 'Type_of_vehicle',
       'multiple_deliveries', 'Festival', 'City', 'Time_taken(min)'],
      dtype='object')

In [231]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41953 entries, 0 to 41952
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           41953 non-null  object
 1   Delivery_person_ID           41953 non-null  object
 2   Delivery_person_Age          40234 non-null  float64
 3   Delivery_person_Ratings      40190 non-null  float64
 4   Restaurant_latitude          41953 non-null  float64
 5   Restaurant_longitude         41953 non-null  float64
 6   Delivery_location_latitude   41953 non-null  float64
 7   Delivery_location_longitude  41953 non-null  float64
 8   Order_Date                   41953 non-null  object
 9   Time_Orderd                  40353 non-null  object
 10  Time_Order_picked            41953 non-null  object
 11  Weatherconditions            41953 non-null  object
 12  Road_traffic_density         41953 non-null  object
 13  Vehicle_condition            41953 non-null  int64
 14  Type_of_order                41953 non-null  object
 15  Type_of_vehicle              41953 non-null  object
 16  multiple_deliveries          41048 non-null  float64
 17  Festival                     41953 non-null  object
 18  City                         41953 non-null  object
 19  Time_taken(min)              41953 non-null  object
dtypes: float64(7), int64(1), object(12)
memory usage: 6.4+ MB

In [232]:
df.sample(5)

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
4818,0x23fd,MUMRES14DEL03,28.0,4.3,19.181300,72.836191,19.211300,72.866191,05-03-2022,22:25:45,22:31:42,conditions Windy,Low,0,Meal,motorcycle,1.0,No,Urban,(min) 25
36100,0x6367,SURRES19DEL02,31.0,4.9,21.149669,72.772629,21.229669,72.852629,02-03-2022,18:45:21,18:55:24,conditions Fog,Medium,0,Snack,motorcycle,3.0,No,Metropolitian,(min) 45
31483,0xbbc4,JAPRES17DEL03,37.0,4.7,26.892312,75.806896,26.982312,75.896896,23-03-2022,22:31:33,22:44:42,conditions Windy,Low,0,Snack,motorcycle,1.0,No,Metropolitian,(min) 29
30669,0x5297,MYSRES08DEL02,38.0,4.3,12.297954,76.665169,12.427954,76.795169,08-03-2022,17:35:09,17:42:55,conditions Stormy,Medium,2,Meal,scooter,1.0,No,Metropolitian,(min) 33
14702,0x745d,BANGRES02DEL01,37.0,4.8,12.970221,77.645396,13.080221,77.755396,31-03-2022,23:46:14,23:56:46,conditions Windy,Low,0,Meal,motorcycle,0.0,No,Metropolitian,(min) 28

In [233]:
df.describe()

,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Vehicle_condition,multiple_deliveries
count,40234.000000,40190.000000,41953.000000,41953.000000,41953.000000,41953.000000,41953.000000,41048.000000
mean,29.563330,4.632386,18.911397,76.923408,18.975064,76.987074,1.022716,0.745249
std,5.812361,0.335541,5.467829,3.502910,5.469616,3.503073,0.838893,0.572152
min,15.000000,1.000000,9.957144,72.768726,9.967144,72.778726,0.000000,0.000000
25%,25.000000,4.500000,12.986047,73.898520,13.065996,73.940327,0.000000,0.000000
50%,30.000000,4.700000,19.065838,76.618203,19.123249,76.663622,1.000000,1.000000
75%,35.000000,4.900000,22.751234,78.368855,22.820040,78.405467,2.000000,1.000000
max,50.000000,6.000000,30.914057,88.433452,31.054057,88.563452,3.000000,3.000000

In [234]:
df.describe(include="object")

,ID,Delivery_person_ID,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Type_of_order,Type_of_vehicle,Festival,City,Time_taken(min)
count,41953,41953,41953,40353,41953,41953,41953,41953,41953,41953,41953,41953
unique,41953,1170,44,25569,26949,7,5,4,4,3,4,45
top,0x4607,JAPRES11DEL02,15-03-2022,19:56:41,21:56:46,conditions Fog,Low,Snack,motorcycle,No,Metropolitian,(min) 26
freq,1,67,1115,8,8,7012,14200,10616,24396,40916,31411,1960

In [235]:
df.dtypes

ID                              object
Delivery_person_ID              object
Delivery_person_Age            float64
Delivery_person_Ratings        float64
Restaurant_latitude            float64
Restaurant_longitude           float64
Delivery_location_latitude     float64
Delivery_location_longitude    float64
Order_Date                      object
Time_Orderd                     object
Time_Order_picked               object
Weatherconditions               object
Road_traffic_density            object
Vehicle_condition                int64
Type_of_order                   object
Type_of_vehicle                 object
multiple_deliveries            float64
Festival                        object
City                            object
Time_taken(min)                 object
dtype: object

In [236]:
numerical_columns = df.select_dtypes(include=["int64", "float64"]).columns
numerical_columns

Index(['Delivery_person_Age', 'Delivery_person_Ratings', 'Restaurant_latitude',
       'Restaurant_longitude', 'Delivery_location_latitude',
       'Delivery_location_longitude', 'Vehicle_condition',
       'multiple_deliveries'],
      dtype='object')

In [237]:
categorical_columns = df.select_dtypes(include=["object"]).columns
categorical_columns

Index(['ID', 'Delivery_person_ID', 'Order_Date', 'Time_Orderd',
       'Time_Order_picked', 'Weatherconditions', 'Road_traffic_density',
       'Type_of_order', 'Type_of_vehicle', 'Festival', 'City',
       'Time_taken(min)'],
      dtype='object')

In [238]:
print("Number of Numerical Columns:", len(numerical_columns))
print("Number of Categorical Columns:", len(categorical_columns))

Number of Numerical Columns: 8
Number of Categorical Columns: 12

In [239]:
df["Time_taken(min)"].head(10)

0    (min) 24
1    (min) 33
2    (min) 26
3    (min) 21
4    (min) 30
5    (min) 26
6    (min) 40
7    (min) 32
8    (min) 34
9    (min) 46
Name: Time_taken(min), dtype: object

In [240]:
df["Time_taken(min)"].value_counts().tail(10)

(min) 47    274
(min) 49    257
(min) 48    256
(min) 46    255
(min) 45    227
(min) 53     89
(min) 54     85
(min) 51     82
(min) 52     73
(min) 50     67
Name: Time_taken(min), dtype: int64

In [241]:
df["Time_taken(min)"].str.strip().sample(5)

39802    (min) 21
14773    (min) 50
1719     (min) 19
11234    (min) 26
8001     (min) 31
Name: Time_taken(min), dtype: object

In [242]:
missing_values = df.isnull().sum()
missing_values

ID                                0
Delivery_person_ID                0
Delivery_person_Age            1719
Delivery_person_Ratings        1763
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Order_Date                        0
Time_Orderd                    1600
Time_Order_picked                 0
Weatherconditions                 0
Road_traffic_density              0
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries             905
Festival                          0
City                              0
Time_taken(min)                   0
dtype: int64

In [243]:
missing_values[missing_values > 0]

Delivery_person_Age        1719
Delivery_person_Ratings    1763
Time_Orderd                1600
multiple_deliveries         905
dtype: int64

In [244]:
missing_percentage = (
    df.isnull().sum() / len(df)
) * 100
missing_percentage[missing_percentage>0]

Delivery_person_Age        4.097442
Delivery_person_Ratings    4.202322
Time_Orderd                3.813792
multiple_deliveries        2.157176
dtype: float64

In [245]:
missing_summary = pd.DataFrame({
    "Missing Count": df.isnull().sum(),
    "Missing Percentage": (
        df.isnull().sum() / len(df)
    ) * 100
})

missing_summary = missing_summary[
    missing_summary["Missing Count"] > 0
]

missing_summary.sort_values(
    by="Missing Percentage",
    ascending=False
)

                         Missing Count  Missing Percentage
Delivery_person_Ratings           1763            4.202322
Delivery_person_Age               1719            4.097442
Time_Orderd                       1600            3.813792
multiple_deliveries                905            2.157176

In [246]:
df["Delivery_person_Age"].unique()[:10]

array([37., 34., 23., 38., 32., 22., 33., 35., 36., 21.])

In [247]:
df["Delivery_person_Ratings"].unique()[:10]

array([4.9, 4.5, 4.4, 4.7, 4.6, 4.8, 4.2, 4.3, 4. , 4.1])

In [248]:
df["Time_Orderd"].sample(5)

39026    13:51:34
14928    10:24:31
13564    20:30:57
5583     17:53:54
18902    20:37:37
Name: Time_Orderd, dtype: object

In [249]:
df["multiple_deliveries"].value_counts(dropna=False)

1.0    25928
0.0    12952
2.0     1841
NaN      905
3.0      327
Name: multiple_deliveries, dtype: int64

In [250]:
duplicate_count = df.duplicated().sum()
print("Duplicate Rows:", duplicate_count)

Duplicate Rows: 0

In [251]:
df["multiple_deliveries"].value_counts(dropna=True)

1.0    25928
0.0    12952
2.0     1841
3.0      327
Name: multiple_deliveries, dtype: int64

In [252]:
df["Time_taken(min)"].value_counts(dropna=False).head()

(min) 26    1960
(min) 25    1899
(min) 27    1826
(min) 29    1795
(min) 28    1794
Name: Time_taken(min), dtype: int64

In [253]:
df.nunique()

ID                             41953
Delivery_person_ID              1170
Delivery_person_Age               22
Delivery_person_Ratings           28
Restaurant_latitude              388
Restaurant_longitude             388
Delivery_location_latitude      4362
Delivery_location_longitude     4362
Order_Date                        44
Time_Orderd                    25569
Time_Order_picked              26949
Weatherconditions                  7
Road_traffic_density               5
Vehicle_condition                  4
Type_of_order                      4
Type_of_vehicle                    4
multiple_deliveries                4
Festival                           3
City                               4
Time_taken(min)                   45
dtype: int64

In [254]:
df.isnull().sum()

ID                                0
Delivery_person_ID                0
Delivery_person_Age            1719
Delivery_person_Ratings        1763
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Order_Date                        0
Time_Orderd                    1600
Time_Order_picked                 0
Weatherconditions                 0
Road_traffic_density              0
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries             905
Festival                          0
City                              0
Time_taken(min)                   0
dtype: int64

In [255]:
df["City"].value_counts(dropna=False)

Metropolitian     31411
Urban              9279
NaN                1114
Semi-Urban          149
Name: City, dtype: int64

In [256]:
object_columns = df.select_dtypes(include="object").columns
# Remove leading and trailing spaces
df[object_columns] = df[object_columns].apply(
    lambda col: col.str.strip()
)

In [257]:
df.head(2)

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
0,0x4607,INDORES13DEL02,37.0,4.9,22.745049,75.892471,22.765049,75.912471,19-03-2022,11:33:33,11:45:29,conditions Sunny,High,2,Snack,motorcycle,0.0,No,Urban,(min) 24
1,0xb379,BANGRES18DEL02,34.0,4.5,12.913041,77.683237,13.043041,77.813237,25-03-2022,19:45:37,19:51:49,conditions Stormy,Jam,2,Snack,scooter,1.0,No,Metropolitian,(min) 33

In [258]:
df["City"].value_counts()

Metropolitian    31411
Urban             9279
NaN               1114
Semi-Urban         149
Name: City, dtype: int64

In [259]:
df[df["Delivery_person_Ratings"] >5].head(2)

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
3283,0x46d,BANGRES05DEL01,50.0,6.0,12.970324,77.645748,13.010324,77.685748,13-03-2022,None,12:34:56,conditions NaN,NaN,3,Meal,electric_scooter,0.0,No,Urban,(min) 25
4315,0x493,HYDRES17DEL01,50.0,6.0,17.451976,78.385883,17.561976,78.495883,04-04-2022,None,23:23:19,conditions NaN,NaN,3,Snack,bicycle,0.0,No,Metropolitian,(min) 27

In [260]:
(df["Delivery_person_Ratings"] > 5).sum()

46

In [261]:
df.loc[df["Delivery_person_Ratings"] > 5,
    "Delivery_person_Ratings"
] = np.nan

In [262]:
df["Delivery_person_Ratings"].value_counts(dropna=False).sort_index(ascending=False).head()

5.0    3666
4.9    6468
4.8    6558
4.7    6528
4.6    6387
Name: Delivery_person_Ratings, dtype: int64

In [263]:
df["Time_taken(min)"].value_counts(dropna=False).head()

(min) 26    1960
(min) 25    1899
(min) 27    1826
(min) 29    1795
(min) 28    1794
Name: Time_taken(min), dtype: int64

In [264]:
# Extract only numeric values
df["Time_taken(min)"] = (
    df["Time_taken(min)"]
      .str.extract(r"(\d+)")
      .astype(int)
)
df["Time_taken(min)"].value_counts(dropna=False).head()

26    1960
25    1899
27    1826
29    1795
28    1794
Name: Time_taken(min), dtype: int64